version: 1.0.{build}
configuration:
- Debug
- Release
platform: x64
before_build:
- cmd: git submodule update --init --recursive
- cmd: build-dependencies.cmd
build:
  parallel: true
  verbosity: minimal